name: CI
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set GitHub user
        run: |
          git config --global user.email aeneasr@users.noreply.github.com
          git config --global user.name aeneasr
      - name: Run update script
        run: ./update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AENEASR }}
